#!/bin/bash
#
# kasutaja lisamise skript
if [ -f kasutajad -a -r kasutajad ]; then
	echo "Fail on korras"
 for rida in $(cat kasutajad)
 do
	# sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd echo asemel tuleb kutsuda vajlik skript
	#echo $rida
	# sh skriptimine $rida
	sh lisa_kasutaja $rida
	done
else
	echo "probleem failiga"
fi
