#!/bin/bash

#
# Loob kasutajale parooli + andmebaasi
kasutaja=$1
parool=$(openssl rand -hex 8)

mycnf=/home/$kasutaja/.my.cnf

# Paneb parooli, et saab mysql ilma logimata sisse, annab õigused andmebaasi serveris
mysql -e "CREATE DATABASE ${kasutaja}"
mysql -e "CREATE USER ${kasutaja}@localhost IDENTIFIED BY '${parool}';"
mysql -e "GRANT ALL PRIVILEGES ON ${kasutaja}.* TO '${kasutaja}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

#
touch $mycnf
echo "[client]
user = $kasutaja
password = $parool
host = localhost" > /home/$kasutaja/.my.cnf
